version: '3'
services:
  web-server:
    build: . 
    image: sunnymean/nginx_njs:latest
    volumes:
      - type: bind
        source: conf/my.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: njs/
        target: /etc/nginx/njs/
      - type: bind
        source: www/
        target: /usr/share/nginx/html
    ports:
      - "80:80"
